// File is autogenerated with `dub run spasm:webidl -- --bindgen`
import * as bindings from './bindings.js';
import * as spa from './spa.js';
import * as spasm from './spasm.js';
const modules = [bindings, spa, spasm];
export { spasm, modules }