// File is autogenerated with `dub spasm:webidl -- --bindgen`
import {spasm as spa, encoders as encoder, decoders as decoder} from '../modules/spasm.js';
let spasm = spa;
let memory = {};
const setupMemory = () => {
    let buffer = spasm.memory.buffer;
    if (memory.heapi32s && !memory.heapi32s.length === 0)
        return;
    memory.heapi32s = new Int32Array(buffer)
    memory.heapi32u = new Uint32Array(buffer)
    memory.heapi16s = new Int16Array(buffer)
    memory.heapi16u = new Uint16Array(buffer)
    memory.heapi8s = new Int8Array(buffer)
    memory.heapi8u = new Uint8Array(buffer)
    memory.heapf32 = new Float32Array(buffer)
    memory.heapf64 = new Float64Array(buffer)
}
const setBool = (ptr, val) => (memory.heapi32u[ptr/4] = +val),
      setInt = (ptr, val) => (memory.heapi32s[ptr/4] = val),
      setUInt = (ptr, val) => (memory.heapi32u[ptr/4] = val),
      setShort = (ptr, val) => (memory.heapi16s[ptr/2] = val),
      setUShort = (ptr, val) => (memory.heapi16u[ptr/2] = val),
      setByte = (ptr, val) => (memory.heapi8s[ptr] = val),
      setUByte = (ptr, val) => (memory.heapi8u[ptr] = val),
      setFloat = (ptr, val) => (memory.heapf32[ptr/4] = val),
      setDouble = (ptr, val) => (memory.heapf64[ptr/8] = val),
      getBool = (ptr) => memory.heapi32u[ptr/4],
      getInt = (ptr) => memory.heapi32s[ptr/4],
      getUInt = (ptr) => memory.heapi32u[ptr/4],
      getShort = (ptr) => memory.heapi16s[ptr/2],
      getUShort = (ptr) => memory.heapi16u[ptr/2],
      getByte = (ptr) => memory.heapi8s[ptr],
      getUByte = (ptr) => memory.heapi8u[ptr],
      getFloat = (ptr) => memory.heapf32[ptr/4],
      getDouble = (ptr) => memory.heapf64[ptr/8],
      isDefined = (val) => (val != undefined && val != null),
      encode_handle = (ptr, val) => { setUInt(ptr, spasm.addObject(val)); },
      decode_handle = (ptr) => { return spasm.objects[getUInt(ptr)]; },
      spasm_encode_string = encoder.string,
      spasm_decode_string = decoder.string,
      spasm_indirect_function_get = (ptr)=>spasm.instance.exports.__indirect_function_table.get(ptr),
  spasm_encode_Handle = encode_handle,
  spasm_encode_optional_Handle = (ptr, val)=>{
    if (setBool(ptr+4, isDefined(val))) {
      spasm_encode_Handle(ptr, val);
    }
  },
  spasm_encode_optional_RenderingContext = (ptr, val)=>{
    if (setBool(ptr+8, isDefined(val))) {
      spasm_encode_union4_CanvasRenderingContext2D_ImageBitmapRenderingContext_WebGLRenderingContext_WebGL2RenderingContext(ptr, val);
    }
  },
  spasm_encode_union4_CanvasRenderingContext2D_ImageBitmapRenderingContext_WebGLRenderingContext_WebGL2RenderingContext = (ptr, val)=>{
    if (val instanceof CanvasRenderingContext2D) {
      setUInt(ptr, 0);
      spasm_encode_Handle(ptr+4, val);
    } else if (val instanceof ImageBitmapRenderingContext) {
      setUInt(ptr, 1);
      spasm_encode_Handle(ptr+4, val);
    } else if (val instanceof WebGLRenderingContext) {
      setUInt(ptr, 2);
      spasm_encode_Handle(ptr+4, val);
    } else if (val instanceof WebGL2RenderingContext) {
      setUInt(ptr, 3);
      spasm_encode_Handle(ptr+4, val);
    }
  };
export let jsExports = {
  env: {
    CanvasText_fillText_0: (ctx, textLen, textPtr, x, y) => {
      setupMemory();
      spasm.objects[ctx].fillText(spasm_decode_string(textLen, textPtr), x, y);
    },
    HTMLCanvasElement_width_Set: (ctx, width) => {
      setupMemory();
      spasm.objects[ctx].width = width;
    },
    HTMLCanvasElement_height_Set: (ctx, height) => {
      setupMemory();
      spasm.objects[ctx].height = height;
    },
    HTMLCanvasElement_getContext_0: (rawResult, ctx, contextIdLen, contextIdPtr) => {
      setupMemory();
      spasm_encode_optional_RenderingContext(rawResult, spasm.objects[ctx].getContext(spasm_decode_string(contextIdLen, contextIdPtr)));
    },
    Document_createElement_0: (ctx, localNameLen, localNamePtr) => {
      setupMemory();
      return spasm.addObject(spasm.objects[ctx].createElement(spasm_decode_string(localNameLen, localNamePtr)));
    },
    Node_appendChild: (ctx, node) => {
      setupMemory();
      return spasm.addObject(spasm.objects[ctx].appendChild(spasm.objects[node]));
    },
    ParentNode_querySelector: (rawResult, ctx, selectorsLen, selectorsPtr) => {
      setupMemory();
      spasm_encode_optional_Handle(rawResult, spasm.objects[ctx].querySelector(spasm_decode_string(selectorsLen, selectorsPtr)));
    },
  }
}