// File is autogenerated with `dub run spasm:webidl -- --bindgen`
import * as spa from './spa.js';
import * as spasm from './spasm.js';
import * as bindings from './bindings.js';
const modules = [spa, spasm, bindings];
export { spasm, modules }