// File is autogenerated with `dub run spasm:webpack-bootstrap`
import * as spasm from './spasm.js';
import * as spa from './spa.js';
import * as audio from './audio.js';
import * as game from './game.js';
import * as webgl from './webgl.js';
const modules = [spasm, spa, audio, game, webgl];
export {
    spasm,
    modules
}
